// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    CarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    CarbonLogout: typeof import('~icons/carbon/logout')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    Login: typeof import('./components/login.vue')['default']
    Register: typeof import('./components/register.vue')['default']
  }
}

export { }
